Added /station route
DartExplore/dallas-by-metro-backend pull request #209
Opened 2023-07-05 22:50 UTC by ZaneBartlett1

closes #175 and closes #128

2023-07-06 00:43 UTC, ZaneBartlett1 commented
So two notes here -
- I did go ahead and add walk time as a filter, but it's optional, so you don't need to implement it. The only reason I did it is because I notice on the front end, it's not waiting for you to hit submit before it filters. I think it's a tad bit clunky to have it that way since none of the other filters have that. If/when that's updated I wasn't sure if it was easier to do on the front end or use the filter
- I did go ahead and just do it based on the number of connections rather than a rail time, like we discussed on a call. The RTFS data is very hard to parse that information out and due to how we got the station connections (not from the RTFS data) it's even harder.

2023-07-06 03:02 UTC, ZaneBartlett1 commented
I updated some stuff so that by default it sorts by level and then alphabetically within levels. This way the stations that are closest will show up near the top. The alphabetically sorting within levels is arbitrary.

2023-07-11 03:14 UTC, Nightwing52 requested changes
Filtering by walkDistance can be eliminated and other minor things. My main question is: what happens when no currentStation is provided to /stations? I believe it throws an error in the service layer, but it should do so by Bean validation.

2023-07-11 03:14 UTC, Nightwing52 commented on src/main/java/com/dallasbymetro/backend/service/StationServiceImpl.java
> +        Comparator<Pair<Station, Integer>> pairComparator = Comparator
Keep it this way because it is more general, but if you wanted to take advantage of the fact DART rail system is a tree (no loops), then each time you iterate you're guaranteed to go up a level.

2023-07-16 19:21 UTC, ZaneBartlett1 commented on src/main/java/com/dallasbymetro/backend/controller/ReadController.java
> +        } catch (Exception e) {
Yes, and I'm open to using something else. This is just default styling from JetBrains native to the IDE. You would just need to turn it on if that's what you're using, otherwise let me know if there's something else you'd want to set up

2023-07-16 19:22 UTC, ZaneBartlett1 commented on src/main/java/com/dallasbymetro/backend/utility/Pair.java
> +public class Pair<T1, T2> {
Ah, missed that. I'll keep it as is for now as you suggest, but thanks for letting me know

2023-07-16 19:29 UTC, ZaneBartlett1 commented on src/main/java/com/dallasbymetro/backend/controller/ReadController.java
> +            @RequestParam(value = "currentStation", required = false) Long currentStation,
Ah, good catch. Right now if you don't provide it, it'll send an error saying that a null station does not exist. I think technically that would be an acceptable error message, but if you're using the route both the current station and the maxStationConnections should be required.

2023-07-16 19:32 UTC, ZaneBartlett1 commented on src/main/java/com/dallasbymetro/backend/controller/ReadController.java
> +            @RequestParam(value = "currentStation", required = false) Long currentStation,
Updated both these fields to required

2023-07-16 19:37 UTC, ZaneBartlett1 commented on src/main/java/com/dallasbymetro/backend/service/StationServiceImpl.java
> +        Optional<Station> stationOptional = stationRepository.findByStationIdIs(currentStation);
Don't think this really matters, but I changed it. It's going to be findByStationId though from JPL auto generated query. The original one was as well

2023-07-16 19:41 UTC, ZaneBartlett1 commented on src/main/java/com/dallasbymetro/backend/service/PointOfInterestService.java
> +    public static boolean doAllPOIsWithinWalkTime(List<PointOfInterest> pois, Integer maxWalkTime) {
I'd like to keep this as an option just because it does make since to include in the API. Since it's set to optional though you are free to disregard it. I'll address your issue below with how the API is filtering. 

Like I mention though I would like to have the front end updated so that it's filtered on button click rather than as the box is updated, since none of the other choices update on selection but rather on submit

2023-07-16 20:32 UTC, ZaneBartlett1 commented on src/main/java/com/dallasbymetro/backend/service/StationServiceImpl.java
> +        if (maxWalkTime != null) {
Ah, fair enough. I've gone ahead and combined the filters.

2023-07-17 20:17 UTC, ZaneBartlett1 commented on src/main/java/com/dallasbymetro/backend/service/PointOfInterestService.java
> +    public static boolean doAllPOIsHaveAmenities(List<PointOfInterest> pois, List<Long> amenityIds) {
Great catch! I've updated the code so that now we should be filtering out at the POI level, and if a station has no POI it gets filtered out.

2023-07-18 00:17 UTC, ZaneBartlett1 commented on src/main/java/com/dallasbymetro/backend/controller/ReadController.java
> +            @RequestParam(value = "currentStation", required = false) Long currentStation,
https://github.com/DartExplore/dallas-by-metro-backend/pull/209/commits/17961823e7c07ee32da2d38f3d6f35ddc30482d5

2023-07-29 16:13 UTC, Nightwing52 approved these changes
Approved.

2023-07-29 16:13 UTC, merged